language: python
python:
  - "3.6"

before_install:
  - pip install pytest pytest-cov coveralls flask

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - source activate test-environment
  - pip install pytest pytest-cov coveralls

script:
  - py.test --cov-report term-missing:skip-covered --cov=geodepy geodepy/tests/

deploy:
  provider: pypi
  on:
    tags: true
  user:
    secure: "f16HHHjWxAtepUnF5P3n8VD9idOwThNVTGrQq9X/QLredCFaoW0u1+nWrMUzbbrAziz+HwwawJpx3KneDgqSy1i9BqC37C+Tm5rWTNCDcADl3JTiOb/VQ58GDkO0JgKWry4tW2H+dNxofB6JcsDokxEpNwcn+H5YAxR25XR4NfiVKadn/si6KhBNZUnBz7xTutbKvPQKKzEPhNYPwWTmTxiLGUBJBzy+2HxQ+0iE1v7rRml3j6ukHWH9VJtOWxd5O1aaLPl+hvUI5Xr/rM4cs+2G9Ln3GOuF6V9AG3XCp8JKkXNVObneRl/bhLNjHSgB/sp+PJyFDNLSZy+Zg9Yir/L4VkLWt15r+1evCesoOpPJwhYf51YBWKMPwu4JyG/tvX3mRr75F/T5LHU0Uy/LsOThCeHhthubV5AZTjffunnBpzE8W62ogu1VCRS995Yqk1n4FJm46+nb+NcTgPIunjRJVRJUGJLQv2+jTf3qmfwEIdNsFHCsGqEiAdG3ZUIs90DonLGWw6spOhsxBqWfCgc97jkc2HG3lZ+hLOTXJoSFUOLzQEM0zr7OUGJGOhLqe4CuTAekFXJcYoOY0QiCLMjMcveOzg5QAFhtuRseazAb7t9L7BrXlueHQ+j5KrMR42lYpWGVxgkgsql945vI5/1MSDGmou80yCYdcQgZBZY="
  password:
    secure: "i63oezmGzlzpxKe+dKqaIaHGQHIcBhxGxG2uyqjNCofbwGc2uDVW8cS58E46YZWjUvraJDjBEVQ028tuMaesyBPsC7mJcGUO/Iwhg3gHXVL3ALVbRzILMdTYwnjA5qmlUwMsyGKh77xqT6J0nWgEJa+Ql1kSoEdH30BU38j6PBgugXCFF4LSwrqI3eE9Y8bcFVzL0AwIvXC55SZ3W91ziby6iV5MgYG+uC/J/CGuKSTcjqBTHA5Tag58J8t6yD0te6XUskgjfduWLUe3/Xtn8B8d/zFrRHJXnZs3RjdlmbMmNSNfHuj2JzYPFWcOX+8jVJozcvUUG9YoF3PsyPZXGqu5npG3hyd5MhjkCEg/+/OwANiuRWEgb8zOdc+wO4tUgd3Y5M8/PrDh9THgfLE5mVU2iXrDIE5BfBvVOLKZp7rAEiZHCFw7KndsQxIuZCxysQu2LWX94HKsqvDMYrboYF6ZHSQ3xzrbh5Ze6Wd3gTwp9UPA7zQ7xLhCYgTxMb6ub54kzLRgjbL/kTGPpk6z+qji5CjZ0viRIiqMPBdAD2Rs6IN7QxXZM5ChcT5v6rup7QXSZhq6afgM2JJgW+DUVIsxpTIaSyMaQR1dz2ZR2Hrrbz216KFVsVwqwjhKEk7ZMs3O6R8cRViFEd39ZniqoKbLRBMuulgO9lhOgl63a/I="

after_success:
  - coveralls
